export const LOAD_SESSIONS_SUCCESS = "LOAD_SESSIONS_SUCCESS";
export const LOAD_SPEAKERS_SUCCESS = "LOAD_SPEAKERS_SUCCESS";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const UPDATE_SPEAKER_SUCCESS = "UPDATE_SPEAKER_SUCCESS";
export const CREATE_SPEAKER_SUCCESS = "CREATE_SPEAKER_SUCCESS";
